sudo: required
services:
  - docker

before_install:
  - docker build -t ekeyur/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ekeyur/react-test npm test -- --coverage

after_success:
  - docker build -t ekeyur/multi-client ./client
  - docker build -t ekeyur/multi-server ./server
  - docker build -t ekeyur/multi-nginx ./nginx
  - docker build -t ekeyur/multi-worker ./worker
# Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push ekeyur/multi-client
  - docker push ekeyur/multi-server
  - docker push ekeyur/multi-nginx
  - docker push ekeyur/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-056394566759
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



